doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\FAQ:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/FAQ'
                prefix: 'App\Entity\FAQ'
                alias: App\FAQ
            App\ECommerce:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/ECommerce'
                prefix: 'App\Entity\ECommerce'
                alias: App\ECommerce
            App\Main:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Main'
                prefix: 'App\Entity\Main'
                alias: App\Main

